version: 2.0

jobs:
  deploy_to_playground:
    docker:
      - image: circleci/python:3.12-stretch
    steps:
      - checkout
      - run:
          name: Add plotly remote
          command: git remote add playground https://dash-playground.plotly.host/GIT/slicer-$CIRCLE_BRANCH
      - run:
          name: Create helper-script
          command: printf '#!/bin/bash\necho username=$PLAYGROUND_DEPLOY_USERNAME\necho password=$PLAYGROUND_DEPLOY_PASSWORD' >> /home/circleci/helper-script.sh
      - run:
          name: Set up git config
          command: |
            git config --global credential.helper "/bin/bash /home/circleci/helper-script.sh"
            git config --global user.email '<>' # Leave email blank
            git config --global user.name "Circle MonoRepo Automatic Deployer"
      - run:
          name: Install curl
          command: |
            sudo apt update
            sudo apt install -y -qq curl
      - run:
          name: Install dds-client
          command: |
            curl -sSL -o dds-client.tgz https://github.com/plotly/dds-client/releases/download/v0.3.0/dds-client_0.3.0_linux_x86_64.tgz
            mkdir $HOME/bin
            tar xzf dds-client.tgz -C $HOME/bin
            chmod +x $HOME/bin/dds-client
      - run:
          name: Deploy
          command: |
            if ! DASH_ENTERPRISE_URL="$DASH_PLAYGROUND_ENTERPRISE_URL" DASH_ENTERPRISE_API_KEY="$DASH_PLAYGROUND_ENTERPRISE_API_KEY" DASH_ENTERPRISE_USERNAME="$PLAYGROUND_DEPLOY_USERNAME" dds-client apps:exists --name "slicer-$CIRCLE_BRANCH" >/dev/null 2>&1; then
              DASH_ENTERPRISE_URL="$DASH_PLAYGROUND_ENTERPRISE_URL" DASH_ENTERPRISE_API_KEY="$DASH_PLAYGROUND_ENTERPRISE_API_KEY" DASH_ENTERPRISE_USERNAME="$PLAYGROUND_DEPLOY_USERNAME" dds-client apps:create --name "slicer-$CIRCLE_BRANCH"
            fi
            # We force push since branches can diverge and playground is a
            # sandbox
            git push --force playground $CIRCLE_BRANCH:master

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy_to_playground:
          filters:
            branches:
              ignore:
              - main
